version: '3.1'

services:

  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: abobus
      POSTGRES_USER: Ebumba
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432